CREATE TABLE `ext_portal_mm_tab_filterset` (
`id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`id_tab` SMALLINT UNSIGNED NOT NULL ,
`id_filterset` SMALLINT UNSIGNED NOT NULL
) ENGINE = MYISAM ;